const rail=document.querySelector('.rail'), menu=document.querySelector('#menu-toggle');
menu.addEventListener('click',()=>{const open=rail.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
rail.addEventListener('click',e=>{const anchor=e.target.closest('a[href^="#"]');if(!anchor)return;const target=document.querySelector(anchor.getAttribute('href'));if(!target)return;e.preventDefault();rail.classList.remove('open');menu.setAttribute('aria-expanded','false');history.pushState(null,'',anchor.hash);target.scrollIntoView({block:'start'});const heading=target.matches('h2,h3')?target:target.querySelector('h2,h3');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}});
document.querySelectorAll('[data-print]').forEach(b=>b.addEventListener('click',()=>window.print()));
const entries=[...document.querySelectorAll('main h2,main h3')].map((h,i)=>{if(!h.id)h.id=`topic-${i}`;let text='',n=h.nextElementSibling;while(n&&!/^H[23]$/.test(n.tagName)){text+=' '+n.textContent;n=n.nextElementSibling;}return{id:h.id,title:h.textContent,text:text.toLowerCase()};});
const search=document.querySelector('#manual-search'),results=document.querySelector('#search-results'),status=document.querySelector('#search-status');
search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();results.replaceChildren();if(!q){status.textContent='';return;}const words=q.split(/\s+/);const found=entries.filter(e=>words.every(w=>(e.title.toLowerCase()+' '+e.text).includes(w)));for(const entry of found.slice(0,8)){const li=document.createElement('li'),a=document.createElement('a');a.href='#'+entry.id;a.textContent=entry.title;li.append(a);results.append(li);}status.textContent=found.length?`${found.length} matching topics${found.length>8?'; showing first 8':''}`:'No matching topics. Try “backup”, “layer” or “Trainer”.';});
search.addEventListener('keydown',e=>{if(e.key==='Escape'){search.value='';search.dispatchEvent(new Event('input'));}if(e.key==='Enter'){const a=results.querySelector('a');if(a){a.click();document.getElementById(a.hash.slice(1))?.scrollIntoView();}}});
const sections=[...document.querySelectorAll('main>.chapter')],navLinks=[...document.querySelectorAll('.chapter-nav a')];
function markActive(){let active=sections[0]?.id;for(const s of sections){if(s.getBoundingClientRect().top<innerHeight*.32)active=s.id;}for(const a of navLinks){const current=a.hash==='#'+active;a.classList.toggle('active',current);current?a.setAttribute('aria-current','location'):a.removeAttribute('aria-current');}}
addEventListener('scroll',markActive,{passive:true});markActive();
const dialog=document.querySelector('#image-dialog'),large=document.querySelector('#large-image'),caption=document.querySelector('#image-caption');let previousFocus;
document.querySelectorAll('figure img').forEach(img=>{let wrapper=img.parentElement;if(wrapper.tagName==='A'){const button=document.createElement('button');button.className='figure-button';button.type='button';wrapper.replaceWith(button);button.append(img);wrapper=button;}else if(wrapper.tagName!=='BUTTON'){const button=document.createElement('button');button.className='figure-button';button.type='button';img.replaceWith(button);button.append(img);wrapper=button;}wrapper.setAttribute('aria-label','Enlarge image: '+img.alt);wrapper.addEventListener('click',()=>{previousFocus=wrapper;large.src=img.src;document.querySelector('#full-image').href=img.src;large.alt=img.alt;caption.textContent=img.alt;dialog.showModal();});const fc=img.closest('figure')?.querySelector('figcaption');if(fc){const hint=document.createElement('span');hint.className='zoom-hint';hint.textContent='Click image to enlarge';fc.append(hint);}});
document.querySelector('#close-image').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>previousFocus?.focus());
// Play visible recordings without a separate control row.
const recordings=[...document.querySelectorAll('figure[data-animation]')].map(figure=>({figure,img:figure.querySelector('img'),visible:false}));
let printing=false;
function setPlayback(record,play){const source=play?record.figure.dataset.animation:record.figure.dataset.poster;if(record.img.getAttribute('src')!==source)record.img.src=source;record.figure.dataset.playing=String(play);}
const recordingObserver=new IntersectionObserver(entries=>{for(const entry of entries){const record=recordings.find(r=>r.figure===entry.target);record.visible=entry.isIntersecting;setPlayback(record,record.visible&&!printing);}}, {threshold:0.15});
recordings.forEach(record=>recordingObserver.observe(record.figure));
addEventListener('beforeprint',()=>{printing=true;recordings.forEach(r=>setPlayback(r,false));});
addEventListener('afterprint',()=>{printing=false;recordings.forEach(r=>setPlayback(r,r.visible));});
